# Generated by Django 5.1.3 on 2024-12-09 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre_score', models.IntegerField(blank=True, help_text='Enter your GRE score.', null=True)),
                ('gmat_score', models.IntegerField(blank=True, help_text='Enter your GMAT score.', null=True)),
                ('undergrad_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('desired_field_of_study', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendation_letters', models.IntegerField(blank=True, null=True)),
                ('campus_rank_1', models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Suburban'), (3, 'Urban')], null=True)),
                ('campus_rank_2', models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Suburban'), (3, 'Urban')], null=True)),
                ('campus_rank_3', models.IntegerField(blank=True, choices=[(1, 'Rural'), (2, 'Suburban'), (3, 'Urban')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='base.room')),
            ],
        ),
    ]
