# Generated by Django 5.1.3 on 2024-12-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gmat_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gre_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
